### ISSUE TITLE
fs.watch recursive

### ISSUE THREAD

**Issue by Refzlund** [ymzuiku/svelte-zero-api#1]
Awesome work!
However, fs.watch recursive [./watch.js(96)] does not work in Linux, and does not work in Node 14

`The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at Object.watch (fs.js:1578:11)
    at default (file:///home/arthur/Gits/cuppy-sveltekit/node_modules/svelte-zero-api/watch.js:96:6)
    at file:///home/arthur/Gits/cuppy-sveltekit/svelte.config.js:7:2
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async load_config (file:///home/arthur/Gits/cuppy-sveltekit/node_modules/@sveltejs/kit/dist/cli.js:502:17)
    at async get_config (file:///home/arthur/Gits/cuppy-sveltekit/node_modules/@sveltejs/kit/dist/cli.js:557:10)
    at async file:///home/arthur/Gits/cuppy-sveltekit/node_modules/@sveltejs/kit/dist/cli.js:615:18
`

https://stackoverflow.com/a/61829462

Perhaps https://stackoverflow.com/a/13705878 could help

**Comment by ymzuiku** [comment]
Thank you so much, i ignore github message, svelte-zero-api@0.2.1 use chokidar in linux.

**Comment by Refzlund** [comment]
> Thank you so much, i ignore github message, svelte-zero-api@0.2.1 use chokidar in linux.

Yo, that's awesome! Nice work!
I'm currently working with **SvelteKit** and your package querystring-number gives error
"module querystring-number does not provide an export named 'default'"

Issue:
(svelte-zero-api/lib/index.ts)
`import qs from "querystring-number";`

Does not export default
